In [0]:
# import library
import numpy as np

In [2]:
np.__version__

'1.16.4'

In [3]:
# How to create a 1D array?
# Create a 1D array of numbers from 0 to 9
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ans = np.arange(10)
ans

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# How to create a boolean array?
# Create a 3×3 numpy array of all True’s

In [6]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
# other way
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [0]:
# How to extract items that satisfy a given condition from 1D array?
# Extract all odd numbers
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[arr %2 ==1]

array([1, 3, 5, 7, 9])

In [10]:
# How to replace items that satisfy a condition with another value in numpy array?
# Replace all odd numbers with -1
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [0]:
# How to replace items that satisfy a condition without affecting the original array?
# Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
# How to reshape an array?
# Convert a 1D array to a 2D array with 2 rows
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.reshape(arr,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
arr.reshape(2,-1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
# How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [17]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# use concatenate
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [22]:
# vstack
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# r_
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# How to stack two arrays horizontally?
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
# hstack
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [28]:
# How to generate custom sequences in numpy without hardcoding?
a = np.array([1,2,3])
a


array([1, 2, 3])

In [29]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [0]:
# How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [31]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [32]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [33]:
np.intersect1d(a,b)

array([2, 4])

In [34]:
# How to remove from one array those items that exist in another?
# From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a

array([1, 2, 3, 4, 5])

In [35]:
b

array([5, 6, 7, 8, 9])

In [36]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [37]:
# How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [38]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [39]:
np.where(a==b)

(array([1, 3, 5, 7]),)

In [40]:
np.where(b==a)

(array([1, 3, 5, 7]),)

In [41]:
# How to extract all numbers between a given range from a numpy array?
# Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [42]:
# index
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [43]:
# use logical_and
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [44]:
# other
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [45]:
# How to make a python function that handles scalars to work on numpy arrays?
# Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [0]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [47]:
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [48]:
# How to swap two columns in a 2d numpy array?
# Swap columns 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [50]:
# Swap rows 1 and 2 in the array arr:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [52]:
# How to reverse the rows of a 2D array?
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [54]:
# How to reverse the columns of a 2D array?
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [55]:
# How to create a 2D array containing random floats between 5 and 10?
np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

array([[5.90303538, 5.30581762, 6.01569499],
       [6.83567948, 5.87893423, 8.40044055],
       [6.17595414, 7.4323929 , 6.89784661],
       [7.43440855, 7.47074582, 9.43809365],
       [9.91482083, 9.64292569, 5.1199556 ]])

In [56]:
# use uniform 
np.random.uniform(5,10, size=(5,3))

array([[5.19863906, 7.5719524 , 6.19864045],
       [5.43678193, 7.59082941, 7.02877253],
       [9.86644235, 8.26667117, 9.20149325],
       [8.37440657, 9.73566567, 9.59823045],
       [7.28770683, 7.20519857, 5.03150422]])

In [57]:
# print only 3 decimal places in python numpy array?
arr = np.random.random((5,3))
arr

array([[0.4791151 , 0.82315205, 0.72722075],
       [0.51986757, 0.1631142 , 0.85814702],
       [0.4235566 , 0.26385618, 0.60881995],
       [0.12115054, 0.85020669, 0.41324875],
       [0.05432266, 0.39736214, 0.14675965]])

In [0]:
np.set_printoptions(precision=3)

In [59]:
arr

array([[0.479, 0.823, 0.727],
       [0.52 , 0.163, 0.858],
       [0.424, 0.264, 0.609],
       [0.121, 0.85 , 0.413],
       [0.054, 0.397, 0.147]])

In [60]:
# suppressing the scientific notation

# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [61]:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [62]:
# limit the number of items printed in output of numpy array?
np.set_printoptions(threshold=6)
np.arange(15)

array([ 0,  1,  2, ..., 12, 13, 14])

In [63]:
# print the full numpy array without truncating
import sys
np.set_printoptions(threshold=sys.maxsize)
np.arange(50)

# np.set_printoptions(threshold=np.nan)
# NOT work in python3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [64]:
np.nan

nan